name: Scraper Morning (Union Territories And Central)

on:
  schedule:
    - cron: "30 9 * * *"
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    env:
      SCARPER_API_TOKEN: ${{ secrets.SCARPER_API_TOKEN}}
      REVERSE_PROXY: ${{ secrets.REVERSE_PROXY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape Union Territories And Central India
        run: python3 -m Scrape.UNION_TERRITORIES_AND_CENTRAL
        continue-on-error: true

      - name: Ensure  Union Territories And Central and JSON file exist
        run: |
          # Create folder if missing
          if [ ! -d "data/UnionTerritoriesAndCentral" ]; then
            echo "ðŸ“ Folder data/UnionTerritoriesAndCentral does not exist. Creating it..."
            mkdir -p data/UnionTerritoriesAndCentral
          fi

          # Create empty JSON only if no JSON exists
          if [ -z "$(ls -1 data/UnionTerritoriesAndCentral/*.json 2>/dev/null)" ]; then
            echo "[]" > data/UnionTerritoriesAndCentral/empty_$(date +'%Y%m%d_%H%M').json
            echo "ðŸ†• Created empty JSON file because folder had no JSON files."
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Union Territories And Central-data
          path: data/UnionTerritoriesAndCentral/*.json
          retention-days: 7

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/UnionTerritoriesAndCentral/ || true
          git diff --staged --quiet || git commit -m "ðŸ“Š UpdateUnionTerritoriesAndCentral data - $(date +'%Y-%m-%d %H:%M')"
          git push || true
